export type Vehicle = {
  id: string;
  name: string;
  brand: string;
  type: 'suv' | 'sedan' | 'electric' | 'sports' | 'truck' | 'luxury';
  price: number;
  year: number;
  mileage: number;
  fuelType: 'electric' | 'gasoline' | 'diesel' | 'hybrid' | 'plugin-hybrid';
  location: string;
  imageUrl: string;
  condition: 'new' | 'used';
  featured?: boolean;
  videoUrl?: string;
};

export const vehicles: Vehicle[] = [
  // Tesla - Electric
  {
    id: '1',
    name: 'Model S Plaid',
    brand: 'Tesla',
    type: 'electric',
    price: 89990,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'San Francisco, CA',
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/x3D1ukrI9eA?si=Cxa_WS8XkgY3gE1x',
  },
  {
    id: '2',
    name: 'Model 3 Long Range',
    brand: 'Tesla',
    type: 'electric',
    price: 45990,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'Los Angeles, CA',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
  },
  {
    id: '3',
    name: 'Model X',
    brand: 'Tesla',
    type: 'suv',
    price: 79990,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'Seattle, WA',
    imageUrl: 'https://images.unsplash.com/photo-1571607388263-1044f9ea01dd?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // BMW - Luxury & Sports
  {
    id: '4',
    name: 'X5 M Competition',
    brand: 'BMW',
    type: 'suv',
    price: 112000,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Miami, FL',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/6AfoTwOSFxw?si=qeBah0mrVgA_G7F5',
  },
  {
    id: '5',
    name: 'M3 Competition',
    brand: 'BMW',
    type: 'sports',
    price: 72800,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'New York, NY',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
  },
  {
    id: '6',
    name: '3 Series 330i',
    brand: 'BMW',
    type: 'sedan',
    price: 43800,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Boston, MA',
    imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // Mercedes-Benz - Luxury
  {
    id: '7',
    name: 'S-Class S 580',
    brand: 'Mercedes-Benz',
    type: 'luxury',
    price: 114500,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Beverly Hills, CA',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/PYOsP4cfBOw?si=WV33DWmFtOn4DsgQ',
  },
  {
    id: '8',
    name: 'GLE 450 4MATIC',
    brand: 'Mercedes-Benz',
    type: 'suv',
    price: 66800,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Houston, TX',
    imageUrl: 'https://images.unsplash.com/photo-1671539267704-2aa63c009fa3?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    condition: 'new',
  },
  {
    id: '9',
    name: 'EQS 450+',
    brand: 'Mercedes-Benz',
    type: 'electric',
    price: 105550,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'San Diego, CA',
    imageUrl: 'https://images.unsplash.com/photo-1609703048009-d3576872b32c?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    condition: 'new',
  },

  // Audi - Luxury & Electric
  {
    id: '10',
    name: 'e-tron GT',
    brand: 'Audi',
    type: 'electric',
    price: 106500,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'Austin, TX',
    imageUrl: 'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/1Xs9ORCwwAA',
  },
  {
    id: '11',
    name: 'Q8 Premium Plus',
    brand: 'Audi',
    type: 'suv',
    price: 72500,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Denver, CO',
    imageUrl: 'https://images.unsplash.com/photo-1654855383391-765987e87c7f?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    condition: 'new',
  },

  // Porsche - Sports & Luxury
  {
    id: '12',
    name: '911 Carrera',
    brand: 'Porsche',
    type: 'sports',
    price: 114200,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Miami, FL',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/8oqEOmUwzMA',
  },
  {
    id: '13',
    name: 'Cayenne Turbo',
    brand: 'Porsche',
    type: 'suv',
    price: 134600,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Scottsdale, AZ',
    imageUrl: 'https://images.unsplash.com/photo-1611651338412-8403fa6e3599?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // Toyota - Reliable & Hybrid
  {
    id: '14',
    name: 'Camry XLE Hybrid',
    brand: 'Toyota',
    type: 'sedan',
    price: 35550,
    year: 2024,
    mileage: 0,
    fuelType: 'hybrid',
    location: 'Portland, OR',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=450&fit=crop',
    condition: 'new',
  },
  {
    id: '15',
    name: 'RAV4 Prime',
    brand: 'Toyota',
    type: 'suv',
    price: 42150,
    year: 2024,
    mileage: 0,
    fuelType: 'plugin-hybrid',
    location: 'Seattle, WA',
    imageUrl: 'https://static1.topspeedimages.com/wordpress/wp-content/uploads/2023/06/2023-rav4-prime-se.jpg',
    condition: 'new',
  },
  {
    id: '16',
    name: 'Highlander Hybrid',
    brand: 'Toyota',
    type: 'suv',
    price: 48130,
    year: 2024,
    mileage: 0,
    fuelType: 'hybrid',
    location: 'San Jose, CA',
    imageUrl: 'https://static1.topspeedimages.com/wordpress/wp-content/uploads/2023/12/toyota-grand-highlander-hybrid-1.jpg',
    condition: 'new',
  },

  // Honda - Reliable
  {
    id: '17',
    name: 'Accord Sport',
    brand: 'Honda',
    type: 'sedan',
    price: 29890,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Chicago, IL',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=450&fit=crop',
    condition: 'new',
  },
  {
    id: '18',
    name: 'CR-V Hybrid',
    brand: 'Honda',
    type: 'suv',
    price: 36450,
    year: 2024,
    mileage: 0,
    fuelType: 'hybrid',
    location: 'Dallas, TX',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // Ford - Trucks & SUVs
  {
    id: '19',
    name: 'F-150 Lightning',
    brand: 'Ford',
    type: 'truck',
    price: 59990,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'Detroit, MI',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=450&fit=crop',
    condition: 'new',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/0PGJvq1HslI',
  },
  {
    id: '20',
    name: 'Mustang Mach-E',
    brand: 'Ford',
    type: 'electric',
    price: 42995,
    year: 2024,
    mileage: 0,
    fuelType: 'electric',
    location: 'Phoenix, AZ',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // Chevrolet
  {
    id: '21',
    name: 'Silverado 1500',
    brand: 'Chevrolet',
    type: 'truck',
    price: 42900,
    year: 2024,
    mileage: 0,
    fuelType: 'gasoline',
    location: 'Nashville, TN',
    imageUrl: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=800&h=450&fit=crop',
    condition: 'new',
  },

  // Lexus - Luxury
  {
    id: '22',
    name: 'RX 450h+',
    brand: 'Lexus',
    type: 'suv',
    price: 59550,
    year: 2024,
    mileage: 0,
    fuelType: 'plugin-hybrid',
    location: 'San Francisco, CA',
    imageUrl: 'https://images.unsplash.com/photo-1625231334168-35067f8853ed?w=800&h=450&fit=crop',
    condition: 'new',
    videoUrl: 'https://www.youtube.com/embed/1svgvmxJKSI?si=AFM1lsGxj_d-36-x',
  },

  // Used vehicles
  {
    id: '23',
    name: 'Model 3',
    brand: 'Tesla',
    type: 'electric',
    price: 35000,
    year: 2022,
    mileage: 25000,
    fuelType: 'electric',
    location: 'Los Angeles, CA',
    imageUrl: 'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=800&h=450&fit=crop',
    condition: 'used',
  },
  {
    id: '24',
    name: 'X3 xDrive30i',
    brand: 'BMW',
    type: 'suv',
    price: 38500,
    year: 2022,
    mileage: 18000,
    fuelType: 'gasoline',
    location: 'Atlanta, GA',
    imageUrl: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&h=450&fit=crop',
    condition: 'used',
  },
];

export const brands = [
  {
    name: 'Tesla',
    logo: '/brands/tesla.svg',
    description: 'Electric Innovation',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/QiK0azAAieU?si=8GRMfLy-_41wwqEc',
  },
  {
    name: 'BMW',
    logo: '/brands/bmw.svg',
    description: 'Ultimate Driving Machine',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/mGRZ23OuQrA?si=HrOYjsRWVUFqD4Kn',
  },
  {
    name: 'Mercedes-Benz',
    logo: '/brands/mercedes.svg',
    description: 'The Best or Nothing',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/-4zsY28t76k?si=kPC-2oTkRY1KuGq5',
  },
  {
    name: 'Audi',
    logo: '/brands/audi.svg',
    description: 'Vorsprung durch Technik',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/8ffXE6_qXqM?si=BQZYGAkegi0WgVnJ',
  },
  {
    name: 'Porsche',
    logo: '/brands/porsche.svg',
    description: 'There Is No Substitute',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/OL_eIZjiLUk?si=fc5j0BN6fd03739m',
  },
  {
    name: 'Ford',
    logo: '/brands/ford.svg',
    description: 'Built Ford Tough',
    featured: true,
    videoUrl: 'https://www.youtube.com/embed/qkBgpEKlsWs?si=0lkVB7egJZlimY3a',
  },
];
